[build]
  command = "npm run build"
  publish = "server/public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "zisi"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/api/:splat"
  status = 200

[[redirects]]
  from = "/s/*"
  to = "/.netlify/functions/app/s/:splat"
  status = 200

[[redirects]]
  from = "/v/*"
  to = "/.netlify/functions/app/v/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
